import NavBar from "./Components/NavBar";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { Auth0Provider } from "@auth0/nextjs-auth0/client";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Auth0Provider>
          <NavBar />
          {children}
        </Auth0Provider>
      </body>
    </html>
  );
}
