import "./globals.css";
import NavBar from "./Components/NavBar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NavBar/>
      <body>
        {children}
      </body>
    </html>
  );
}
